#!/usr/bin/env bash
# Poster layout regression check.
#
# Compiles the poster across a matrix of realistic inputs (languages, column
# counts, title lengths, optional subtitle/supervisor, orientation) and asserts
# that every one of them still fits on a SINGLE A1 page. A variant that spills
# onto a second page is a layout regression and fails the run.
#
# The driver document is generated into tmp/ with the current template version
# substituted, and compiled against the installed @preview/isc-hei-poster package.
# Run `just install-symblinks` (local dev) or `just pack` (release) first so the
# package is resolvable. Invoked by `just test`, `just test-poster` and `just test-all`.
set -eu

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd -P)"
source "$SCRIPT_DIR/test-helpers.sh"   # provides ROOT and typst_template_version

PACKAGE_VERSION="$(typst_template_version "poster")"
WORK="$ROOT/tmp/isc-hei-poster-variants"
GEN="$WORK/gen.typ"

rm -rf "$WORK"
mkdir -p "$WORK/out"

# ── Generate the parametrized driver (version pinned to the packed package) ──
cat > "$GEN" <<TYPST
// AUTO-GENERATED by scripts/test-poster-variants.sh — do not edit by hand.
// Parameters come from --input; image paths are typst-root-absolute.
#import "@preview/isc-hei-poster:${PACKAGE_VERSION}": isc-poster, isc-card, isc-colbreak

#let arg(k, default) = sys.inputs.at(k, default: default)
#let lang   = arg("lang", "fr")
#let cols   = int(arg("cols", "2"))
#let title  = arg("title", "long")
#let sub    = arg("sub", "yes")
#let sup    = arg("sup", "yes")
#let orient = arg("orient", "portrait")
#let load   = arg("load", "medium")
#let reps   = int(arg("reps", str((light: 1, medium: 2, heavy: 5).at(load))))
#let n-cards = int(arg("cards", str(if cols == 3 { 9 } else { 6 })))

#let titles = (
  fr: (short: [Apprentissage fédéré médical],
       long:  [Apprentissage fédéré pour la protection de la vie privée dans l'analyse de données médicales hospitalières],
       sub:   [Confidentialité différentielle et agrégation distribuée des gradients]),
  en: (short: [Medical Federated Learning],
       long:  [Federated Learning for Privacy-Preserving Analysis of Hospital Medical Records at Scale],
       sub:   [Differential privacy and distributed gradient aggregation]),
  de: (short: [Föderiertes medizinisches Lernen],
       long:  [Föderiertes Lernen zum Schutz der Privatsphäre bei der Analyse medizinischer Krankenhausdaten],
       sub:   [Differentielle Privatsphäre und verteilte Gradientenaggregation]),
)
#let H = (
  fr: ("Résumé", "Introduction", "Méthodologie", "Résultats", "Discussion", "Conclusion", "Perspectives", "Remerciements", "Références"),
  en: ("Abstract", "Introduction", "Methodology", "Results", "Discussion", "Conclusion", "Future work", "Acknowledgements", "References"),
  de: ("Zusammenfassung", "Einleitung", "Methodik", "Ergebnisse", "Diskussion", "Fazit", "Ausblick", "Danksagung", "Referenzen"),
)
#let prose = (
  fr: [Les dossiers de santé électroniques ne peuvent être centralisés sans risque juridique et éthique. Ce travail présente un cadre d'apprentissage fédéré intégrant la confidentialité différentielle et une agrégation robuste aux nœuds défaillants, évalué sur trois cohortes hospitalières.],
  en: [Electronic health records cannot be centralised without legal and ethical risk. This work presents a federated learning framework with differential privacy and aggregation robust to failing nodes, evaluated on three hospital cohorts.],
  de: [Elektronische Gesundheitsakten können nicht ohne rechtliches und ethisches Risiko zentralisiert werden. Diese Arbeit stellt ein föderiertes Lernframework mit differentieller Privatsphäre und robuster Aggregation vor, evaluiert an drei Krankenhauskohorten.],
)
#let body-text = lang => { for _ in range(reps) [#prose.at(lang) ] }
#let fig-card = figure(image("/src/figs/made.svg", height: 6cm, fit: "contain"),
  caption: [Connectivity graph across participating sites.])
#let tbl-card = table(columns: (1fr, auto, auto), inset: 7pt,
  table.header([*Method*], [*AUC*], [*Rounds*]),
  [FedAvg], [0.84], [50], [FedAvg + DP], [0.82], [80], [*Hybrid*], [*0.91*], [*60*])

#let _hbase = H.at(lang)
#let headings = range(n-cards).map(i => _hbase.at(calc.rem(i, _hbase.len())))

#show: isc-poster.with(
  title: titles.at(lang).at(title),
  subtitle: if sub == "yes" { titles.at(lang).sub } else { none },
  student: "Barbara Liskov",
  permanent-email: "barbara.liskov@hevs.ch",
  supervisor: if sup == "yes" { "Prof. Dr John von Neumann" } else { none },
  expert: "Prof. Dr Grace Hopper",
  thesis-id: "ISC-ID-26-1",
  academic-year: "2025-2026",
  major: "Data Engineering",
  orientation: orient,
  language: lang,
  num-columns: cols,
  distribute-columns: true,
)

#let cards-per-col = calc.ceil(n-cards / cols)
#for (i, h) in headings.enumerate() {
  if i > 0 and calc.rem(i, cards-per-col) == 0 { isc-colbreak() }
  isc-card(title: h)[
    #body-text(lang)
    #if i == 1 { fig-card }
    #if i == 2 { tbl-card }
  ]
}
TYPST

# ── Matrix: every entry MUST fit on one page (within the known content budget:
#    portrait holds 9+ cards; landscape ~6 cards max). ──────────────────────
fail=0
printf "%-44s %-6s %s\n" "VARIANT" "PAGES" "STATUS"
printf '%.0s-' {1..64}; echo

check() {
  local name="$1"; shift
  local args=()
  for kv in "$@"; do args+=(--input "$kv"); done
  local pdf="$WORK/out/$name.pdf" log
  if ! log=$(typst compile "${args[@]}" --root "$ROOT" "$GEN" "$pdf" 2>&1); then
    printf "%-44s %-6s %s\n" "$name" "-" "COMPILE-FAIL"
    echo "$log" | head -3 | sed 's/^/      /'
    fail=1; return
  fi
  local pages
  pages=$(pdfinfo "$pdf" 2>/dev/null | awk '/^Pages:/{print $2}')
  if [ "$pages" = "1" ]; then
    printf "%-44s %-6s %s\n" "$name" "$pages" "ok"
  else
    printf "%-44s %-6s %s\n" "$name" "$pages" "OVERFLOW ✗"
    fail=1
  fi
}

# Languages × columns (portrait, realistic content within budget)
for lang in fr en de; do
  check "lang-${lang}_2col" lang=$lang cols=2 cards=6 reps=2
done
check "lang-en_3col" lang=en cols=3 cards=9 reps=1
check "lang-fr_3col" lang=fr cols=3 cards=6 reps=2
# Title length
check "title-short_2col" title=short cols=2 cards=6 reps=2
check "title-long_2col"  title=long  cols=2 cards=6 reps=2
# Subtitle on/off
check "sub-yes_2col" sub=yes cols=2 cards=6 reps=2
check "sub-no_2col"  sub=no  cols=2 cards=6 reps=2
# Supervisor on/off
check "sup-yes_2col" sup=yes cols=2 cards=6 reps=2
check "sup-no_2col"  sup=no  cols=2 cards=6 reps=2
# Landscape (tighter vertical budget — keep to ~6 cards, light text)
check "landscape_2col" orient=landscape cols=2 cards=6 reps=1
check "landscape_3col" orient=landscape cols=3 cards=6 reps=1
check "landscape_long-title_2col" orient=landscape cols=2 cards=5 title=long reps=1

echo
if [ "$fail" -ne 0 ]; then
  echo "FAIL: at least one poster variant overflowed onto a second page." >&2
  echo "Inspect PDFs in: ${WORK#$ROOT/}/out/" >&2
  exit 1
fi
echo "PASS: all poster variants fit on a single A1 page."
